@file:OptIn(FlowPreview::class)

package com.godaddy.commerce.services.sample.catalog.product.create

import android.os.Bundle
import androidx.lifecycle.viewModelScope
import com.godaddy.commerce.catalog.model.CatalogProduct
import com.godaddy.commerce.services.sample.catalog.onSuccess
import com.godaddy.commerce.services.sample.common.util.SkuFormatter
import com.godaddy.commerce.services.sample.common.util.DEFAULT_CURRENCY_CODE
import com.godaddy.commerce.services.sample.common.extensions.onError
import com.godaddy.commerce.services.sample.common.viewmodel.CommonState
import com.godaddy.commerce.services.sample.common.viewmodel.CommonViewModel
import com.godaddy.commerce.services.sample.common.viewmodel.ToolbarState
import com.godaddy.commerce.services.sample.di.CommerceDependencyProvider.getCatalogService
import com.godaddy.commercecore.models.InventoryInfo
import com.godaddy.commercecore.models.Money
import com.godaddy.commercecore.models.PricingInfo
import com.godaddy.commercecore.models.Product
import com.godaddy.commercecore.models.SellableProduct
import kotlinx.coroutines.FlowPreview
import kotlinx.coroutines.suspendCancellableCoroutine


class ProductCreateViewModel : CommonViewModel<ProductCreateViewModel.State>(State()) {
    private val catalogServiceClient = getCatalogService(viewModelScope)
    private val skuFormatter = SkuFormatter()

    private fun setMoneyValue(value: Long): Money{
        return Money(DEFAULT_CURRENCY_CODE, value)
    }

    fun onProductLabelChanged(value: String) {
        update { copy(label = value) }
    }
    fun onProductPriceChanged(value: String){
        value.toLongOrNull()?.let {
            update { copy(
                price = setMoneyValue(it)
            ) }
        }
    }
    fun onProductSalePriceChanged(value: String){
        value.toLongOrNull()?.let {
            update { copy(
                salePrice = setMoneyValue(it)
            ) }
        }
    }

    fun onProductQuantityChanged(value: String){
        value.toIntOrNull()?.let {
            update { copy(quantity = it)} }
    }
    fun onProductThresholdChanged(value: String){
        value.toIntOrNull()?.let {
            update { copy(threshold = it)}
        }
    }

    fun createProduct() {
        execute {
            val label = requireNotNull(state.label)
            val shortLabel = requireNotNull(label.take(DEFAULT_PRODUCT_SHORT_LABEL_SIZE))
            val disablePriceOverride = true
            val pricingInfos = listOf(PricingInfo(
                price = state.price,
                salePrice = state.salePrice
            ))
            val enableInventoryTracking = (state.quantity == null)
            val inventoryInfos = listOf(InventoryInfo(
                quantity = state.quantity,
                threshold = state.threshold,
            ))
            val skuCode = skuFormatter.getSkuAutoGenerated(label)
            val sellableProducts = listOf(SellableProduct(
                label = label,
                shortLabel = shortLabel,
                skuCode = skuCode,
                pricingInfos = pricingInfos,
                inventoryInfos = inventoryInfos,
                disablePriceOverride = disablePriceOverride,
                enableInventoryTracking = enableInventoryTracking,
                attributeValues = emptyList() ,
                status = DEFAULT_PRODUCT_STATUS
            ))
            val product = Product(
                label = label,
                shortLabel = shortLabel,
                pricingInfos = pricingInfos,
                sellableProducts = sellableProducts,
                type = DEFAULT_PRODUCT_TYPE,
                status = DEFAULT_PRODUCT_STATUS,
                sellInPerson = true,
            )

            val request = CatalogProduct(product)
            val catalogService = catalogServiceClient.getService().getOrThrow()

            val response = suspendCancellableCoroutine<CatalogProduct?> {
                catalogService.createCatalogProduct(
                    request,
                    Bundle.EMPTY,
                    it.onSuccess(),
                    it.onError()
                )
            }

            update { copy (
                createdProductId = response?.product?.id,
                createdSellableProductId = response?.product?.sellableProducts?.first()?.id
            )}
        }
    }

    data class State(
        override val commonState: CommonState = CommonState(),
        override val toolbarState: ToolbarState = ToolbarState(title = "Create Product"),

        val label: String? = null,
        val skuCode: String? = null,
        val price: Money? = null,
        val salePrice: Money? = null,
        val quantity: Int? = null,
        val threshold: Int? = null,
        val sellInPerson: Boolean? = true,
        val createdProductId: String? = null,
        val createdSellableProductId: String? = null

    ) : ViewModelState
    companion object{
        private const val DEFAULT_PRODUCT_STATUS = "ACTIVE"
        private const val DEFAULT_PRODUCT_TYPE = "PHYSICAL"
        private const val DEFAULT_PRODUCT_SHORT_LABEL_SIZE = 5
    }
}