@file:OptIn(FlowPreview::class)

package com.godaddy.commerce.services.sample.catalog.product.create

import android.os.Bundle
import androidx.lifecycle.viewModelScope
import com.godaddy.commerce.catalog.model.CatalogProduct
import com.godaddy.commerce.services.sample.catalog.onSuccess
import com.godaddy.commerce.services.sample.catalog.product.SkuFormatter
import com.godaddy.commerce.services.sample.common.extensions.onError
import com.godaddy.commerce.services.sample.common.viewmodel.CommonState
import com.godaddy.commerce.services.sample.common.viewmodel.CommonViewModel
import com.godaddy.commerce.services.sample.common.viewmodel.ToolbarState
import com.godaddy.commerce.services.sample.di.CommerceDependencyProvider.getCatalogService
import com.godaddy.commercecore.models.InventoryInfo
import com.godaddy.commercecore.models.Money
import com.godaddy.commercecore.models.PricingInfo
import com.godaddy.commercecore.models.Product
import com.godaddy.commercecore.models.SellableProduct
import kotlinx.coroutines.FlowPreview
import kotlinx.coroutines.suspendCancellableCoroutine

class ProductCreateViewModel : CommonViewModel<ProductCreateViewModel.State>(State()) {

    private val catalogServiceClient = getCatalogService(viewModelScope)
    val skuFormatter = SkuFormatter()

    // TODO @Noah: checkout refactoring for consumeAction implementation
    fun onProductLabelChanged(value: String) {
        update { copy(label = value) }
    }
    fun onProductPriceChanged(value: String){
        update { copy(price = Money(value = value.toLong(), currencyCode = "USD"))}
    }
    fun onProductSalePriceChanged(value: String){
        update { copy(salePrice = Money(value = value.toLong(), currencyCode = "USD"))}
    }
    fun onProductQuantityChanged(value: String){
        update { copy(quantity = value.toInt())}
    }
    fun onProductThresholdChanged(value: String){
        update { copy(quantity = value.toInt())}
    }
    fun createProduct() {
        execute {
            val label = requireNotNull(state.label)
            val shortLabel = requireNotNull(label.take(5))
            val disablePriceOverride = (state.price == null)
            val pricingInfos = listOf(PricingInfo(
                price = state.price,
                salePrice = state.salePrice
            ))
            val enableInventoryTracking = (state.quantity == null)
            val inventoryInfos = listOf(InventoryInfo(
                quantity = state.quantity,
                threshold = state.threshold,
            ))

             val skuCode = skuFormatter.getSkuAutoGenerated(label)

            //attributes, attribute values, cost,
            val sellableProducts = listOf(SellableProduct(
                label = label,
                shortLabel = shortLabel,
                skuCode = skuCode,
                pricingInfos = pricingInfos,
                inventoryInfos = inventoryInfos,
                disablePriceOverride = disablePriceOverride,
                enableInventoryTracking = enableInventoryTracking,
                attributeValues = emptyList() ,
                status = "ACTIVE",
            ))

            //Price Range?
            val product = Product(
                label = label,
                shortLabel = shortLabel,
                pricingInfos = pricingInfos, // Pricing infos should be here if no attribtues
                sellableProducts = sellableProducts,
                type = "PHYSICAL",
                status = "ACTIVE",
                sellInPerson = true
            )

            val request = CatalogProduct(product)
            val catalogService = catalogServiceClient.getService().getOrThrow()

            // create product
            val response = suspendCancellableCoroutine<CatalogProduct?> {
                catalogService.createCatalogProduct(
                    request,
                    Bundle.EMPTY,
                    it.onSuccess(),
                    it.onError()
                )
            }
            update { copy (
                createdProductId = response?.product?.id,
                createdSellableProductId = response?.product?.sellableProducts?.first()?.id
            )}


        }
    }

    data class State(
        override val commonState: CommonState = CommonState(),
        override val toolbarState: ToolbarState = ToolbarState(title = "Create Product"),

        val label: String? = null,
        val skuCode: String? = null,
        val price: Money? = null,
        val salePrice: Money? = null,
        val quantity: Int? = null,
        val threshold: Int? = null,
        val sellInPerson: Boolean? = true,
        val createdProductId: String? = null,
        val createdSellableProductId: String? = null

    ) : ViewModelState
}