package com.godaddy.commerce.services.sample.catalog.product.create

import java.text.Normalizer
import java.util.Locale

/**
 * Utilities to manipulate Sku related string.
 */
class SkuFormatter {
    private val regexUnaccent = "\\p{InCombiningDiacriticalMarks}+".toRegex()

    fun String.trimDuplicateSymbol(char: Char): String = replace("$char+".toRegex(), char.toString())
    fun CharSequence.unaccent(): String {
        val temp = Normalizer.normalize(this, Normalizer.Form.NFD)
        return regexUnaccent.replace(temp, "")
    }

    /**
     * Sanitize SKU input from the user, before user is done with typing.
     */
    private fun sanitizeInput(sku: String) = sku
        .trimStart()
        .replace(" ", "-")
        .trimDuplicateSymbol('-')
        .unaccent()
        .filterAllowedCharacters()
        .replace(VOWEL_FILTER.toRegex(), "")
        .uppercase(Locale.getDefault())
        .take(MAX_LENGTH)


    /**
     * Generates SKU from the productName
     */
    fun getSkuAutoGenerated(name: String) = name
        .trim()
        .replace(" ", "-")
        .trimDuplicateSymbol('-')
        .unaccent()
        .lowercase(Locale.getDefault())
        .filterAllowedCharacters()
        .take(MAX_LENGTH)

    /**
     * create sku with prefix from 2 parts(name, sku or parentSku + child name)
     * @param leftPart - left part of the sku prefix
     * @param rightPart - right part of the sku prefix
     */
    fun createSkuWithPrefix(leftPart: String, rightPart: String): String {
        val sanitizedLeftPart = sanitizeInput(leftPart)
        val sanitizedRightPart = sanitizeInput(rightPart)
        return when {
            sanitizedLeftPart.isBlank() -> sanitizedRightPart
            sanitizedRightPart.isBlank() -> sanitizedLeftPart
            sanitizedRightPart.startsWith("-") || sanitizedLeftPart.endsWith("-") -> sanitizedLeftPart + sanitizedRightPart
            else -> "$sanitizedLeftPart-$sanitizedRightPart"
        }
    }

    /**
     * Creates sku prefix based on sanitized product name and sanitized sku
     * @param rawName - name of the product before removing all invalid symbols
     * @param rawSku - sku of the product before removing all invalid symbols
     */
    fun createSkuPrefix(rawName: String, rawSku: String): String {
        val sanitizedName = sanitizeInput(rawName)
        val sanitizedSku = sanitizeInput(rawSku)
        // added dash to separate prefix and sku
        return when {
            sanitizedSku.startsWith("-") && sanitizedName.endsWith("-") -> sanitizedName.substring(0, sanitizedName.length - 1)
            sanitizedSku.isBlank() || sanitizedSku.startsWith("-") || sanitizedName.endsWith("-") -> sanitizedName
            else -> "$sanitizedName-"

        }
    }


    private fun String.filterAllowedCharacters() = this.filter {
        it.isLetterOrDigit() || it == '-' || it == '_'
    }

    companion object {
        /** Max length */
        private const val MAX_LENGTH = 128
        private const val VOWEL_FILTER = "[aeiouAEIOU]"
    }

}